/* Copyright (C) 2015 Erik Källman */
/* This file is part of the scttr program. */

/* scttr is free software: you can redistribute it and/or modify */
/* it under the terms of the GNU Lesser General Public License as published by */
/* the Free Software Foundation, either version 3 of the License, or */
/* (at your option) any later version. */

/* scttr is distributed in the hope that it will be useful, */
/* but without any warranty; without even the implied warranty of */
/* merchantability or fitness for a particular purpose. See the */
/* GNU Lesser General Public License for more details. */

/* You should have received a copy of the GNU Lesser General Public License */
/* along with scttr, found in the "license" subdirectory of the root */
/* directory of the scttr program. */
/* If not, see <http://www.gnu.org/licenses/>. */
/**
   * @file formats.h
   * @author Erik Källman
   * @date November 2015
   * @brief All formats used by the program have suffixes that are stored in
   * this file for easy reference.
   */
#ifndef INPUT_FORMATS
#define INPUT_FORMATS

#define MOLCAS_FORMAT ".log" /**< format suffix for output generated by the Molcas program. */
#define TMP_FORMAT ".tmp" /**< suffix for tmp files generated from Scttr. */

#endif /* INPUT_FORMATS */
